name: manual-build
run-name: Manual build of docs from @${{ inputs.repository }}/@${{ inputs.ref }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository where CLML schema is located (default: legislation/clml-schema)'
        required: true
        default: 'legislation/clml-schema'
        type: string
      ref:
        description: 'Branch, tag or commit to use to build documentation (default: master)'
        required: true
        default: 'master'
        type: string
      deploy_repository:
        description: 'Repository to which to deploy generated documentation (default: legislation/clml-schema)'
        required: true
        default: 'legislation/clml-schema'
        type: string
      deploy_branch:
        description: 'Branch to which to deploy documentation (default: github-pages)'
        required: true
        default: 'github-pages'
        type: string
      java_version:
        description: 'Version of Java to use to build documentation (default: 17)'
        required: true
        default: '17'
        type: string
      oxygen_version:
        description: 'Version of oXygen to use to build documentation (default: 25.1)'
        required: true
        default: '25.1'
        type: string
      deploy_pat:
        description: 'GitHub personal access token to use to deploy generated documentation (default: the value of the repository secret PAGES_DEPLOY_PAT)'
        type: string
      debug:
        description: 'Enable additional debug logging'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout documentation generator
        uses: actions/checkout@v3
        with:
          path: generator
      - name: Checkout CLML schema
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: clml-schema
      - name: Setup Java ${{ inputs.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ inputs.java_version }}
      - name: Setup oXygen Scripting ${{ inputs.oxygen_version }}
        run: |
          echo "::group::Downloading oXygen ${{ inputs.oxygen_version }}"
          wget --no-verbose "https://archives.oxygenxml.com/Oxygen/Editor/InstData${OXYGEN_VERSION}/All/oxygen.tar.gz"
          echo "::endgroup::"
          echo "::group::Extracting oXygen"
          tar xf oxygen.tar.gz --one-top-level
          echo "::endgroup::"
          echo "::group::Applying oXygen licence"
          echo "$OXYGEN_LICENCE_KEY" > oxygen/scriptinglicensekey.txt
          echo "::endgroup::"
        env:
          OXYGEN_LICENCE_KEY: ${{ secrets.OXYGEN_LICENCE_KEY }}
          OXYGEN_VERSION: ${{ inputs.oxygen_version }}
      - name: Set paths in transformation scenario
        run: sed -i -E "s#%%WORKSPACE%%#${GITHUB_WORKSPACE}#g" "${GITHUB_WORKSPACE}/generator/generator.xpr"
      - name: Run schema documentation generator transform
        run: '"${GITHUB_WORKSPACE}/oxygen/scripts/transform.sh" -i "${GITHUB_WORKSPACE}/generator/schemaDocAutomator/generateSchemaDoc.xpl" -sn generateSchemaDoc -s "${GITHUB_WORKSPACE}/generator/generator.xpr" -v'
      - name: 'Rename welcome.html to index.html (if required)'
        run: test -f "${GITHUB_WORKSPACE}/final-output/welcome.html" && test ! -f "${GITHUB_WORKSPACE}/final-output/index.html" && mv "${GITHUB_WORKSPACE}/final-output/welcome.html" "${GITHUB_WORKSPACE}/final-output/index.html"
      - name: List all files in workspace
        if: inputs.debug
        run: find "${GITHUB_WORKSPACE}"
      - name: Print transformation scenario
        if: inputs.debug
        run: cat "${GITHUB_WORKSPACE}/generator/generator.xpr"

  deploy:
    needs: build
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages (using provided PAT)
        if: inputs.deploy_pat != ''
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: final-output
          token: ${{ inputs.deploy_pat }}
          branch: ${{ inputs.deploy_branch }}
          repository-name: ${{ inputs.deploy_repository }}
      - name: Deploy to GitHub Pages (using default PAT in repository secret)
        if: inputs.deploy_pat == ''
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: final-output
          token: ${{ secrets.PAGES_DEPLOY_PAT }}
          branch: ${{ inputs.deploy_branch }}
          repository-name: ${{ inputs.deploy_repository }}
